"""empty message

Revision ID: 28fa1cbca62d
Revises: 546d96cd13ec
Create Date: 2014-10-11 12:48:35.195348

"""

# revision identifiers, used by Alembic.
revision = '28fa1cbca62d'
down_revision = '546d96cd13ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('app_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'app_url')
    ### end Alembic commands ###
