"""empty message

Revision ID: 2a6f8061775d
Revises: None
Create Date: 2014-10-02 11:35:08.102667

"""

# revision identifiers, used by Alembic.
revision = '2a6f8061775d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    ### end Alembic commands ###
