"""empty message

Revision ID: 546d96cd13ec
Revises: 2a6f8061775d
Create Date: 2014-10-03 04:06:59.276897

"""

# revision identifiers, used by Alembic.
revision = '546d96cd13ec'
down_revision = '2a6f8061775d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('error_code', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'error_code')
    ### end Alembic commands ###
